logging:
  level:
    root: INFO

spring:
  profiles:
    active: local

#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      group-id: group_id
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    producer:
#      bootstrap-servers: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#
#  cloud:
#    stream:
#      kafka:
#        binder:
#          brokers: localhost:9092
#      bindings:
#        greetings-in:
#          destination: greetings
#          contentType: application/json
#        greetings-out:
#          destination: greetings
#          contentType: application/json

kafka:
  host: localhost
  port: 9092
  topic: kkc_message

server:
  port: 8085
